server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    username: root
    password: 2002
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signer-key: N2MuevBzxX0Y4UnKnyzdLs46IA7hlmG4t0eRkkLB3Mm5v/Yg3PT9tKsUpDZV2SVf

